# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Hany Essam'
tagline:          'Self-Taught .Net developer'
description:      'Having a career shift into Software Development'
url:              https://github.com/Hany3ssam/MyBlog
baseurl:          '/'
paginate:         5

author:
  name: 'Hany Essam'
  email: 'hanyessam1[at]gmail[dot]com'
  github: hany3ssam
  #twitter: pesteadman
  linkedin: hanyessam
  #goodreads: pesteadman
  #orcid: http://orcid.org/0000-0002-5814-4977
  #google_scholar: http://scholar.google.ca/citations?user=Xrn76pEAAAAJ
  #email_md5: 4a424eaac867c7c43ac960ad6650bfd1
  #disqus_shortname: patricksteadman
  #google_analytics_id: UA-27104497-1
  #google_analytics_url: patricksteadman.ca
  bio: Self-Taught junior .Net Developer

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
