# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Hany Essam'
tagline:          'self-taught software developer'
description:      'Self-Taught Software Developer having a career shift from Sales.'
url:              https://hany3ssam.github.io
baseurl:          '/'
gems:             [jekyll-redirect-from]
gems:             [jekyll-paginate]
paginate:         5

author:
  name: 'Hany Essam'
  email: 'hanyessam1[at]gmail[dot]com'
  github: hany3ssam
  linkedin: hanyessam
  bio: Self-Taught junior Software Developer

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
