# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Patrick Steadman'
tagline:          'MD/PhD student at The University of Toronto'
description:      'A student with too many interests'
url:              http://patricksteadman.ca
baseurl:          '/'
paginate:         5

author:
  name: 'Patrick Steadman'
  email: patrick.steadman@mail.utoronto.ca
  github: psteadman
  twitter: pesteadman
  linkedin: pesteadman
  goodreads: pesteadman
  email_md5: 4a424eaac867c7c43ac960ad6650bfd1
  disqus_shortname: patricksteadman
  google_analytics_id: UA-27104497-1
  google_analytics_url: patricksteadman.ca
  bio: MD/PhD student at The University of Toronto

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
